(define (problem problem)

  (:domain 'domain-problem')
  (:objects s0_handler_cleaning_0 - state s1_handler_film_deposition_0 - state s2_handler_resist_coating_0 - state s3_handler_exposure_0 - state s3_handler_exposure_broken - state)
  (:init 
    (current_state_0 s0_handler_cleaning_0)
    (current_state_1 s1_handler_film_deposition_0)
    (current_state_2 s2_handler_resist_coating_0)
    (current_state_3 s3_handler_exposure_0)
    (startsymb)
    (q_1)
    (f_copy)
    (f_ok)
  )
  (:goal (and (current_state_0 s0_handler_cleaning_0)  (current_state_1 s1_handler_film_deposition_0)  (current_state_2 s2_handler_resist_coating_0)  (current_state_3 s3_handler_exposure_0) 
    (not 
      (q_31))
    (q_1d)
    (q_26d)
    (q_2d)
    (q_3d)
    (q_4d)
    (q_30d)
    (q_5d)
    (q_23d)
    (q_6d)
    (q_22d)
    (q_7d)
    (q_8d)
    (q_9d)
    (q_28d)
    (q_10d)
    (q_25d)
    (q_11d)
    (q_22d)
    (q_12d)
    (q_13d)
    (q_14d)
    (q_27d)
    (q_15d)
    (q_25d)
    (q_16d)
    (q_23d)
    (q_17d)
    (q_18d)
    (q_19d)
    (q_29d)
    (q_20d)
    (q_25d)
    (q_21d)
    (q_23d)
    (q_22d)
    (q_24d)
    (q_24d)
    (q_24d)))

)