(define (domain 'domain-problem')
  (:types
    state - NO_TYPE
    action - NO_TYPE
  )

  (:predicates
    (current_state_0 ?x0 - state)
    (current_state_1 ?x0 - state)
    (current_state_2 ?x0 - state)
    (current_state_3 ?x0 - state)
    (current_state_4 ?x0 - state)
    (current_state_5 ?x0 - state)
    (current_state_6 ?x0 - state)
    (current_state_7 ?x0 - state)
    (current_state_8 ?x0 - state)
    (activation)
    (cleaning)
    (development)
    (etching)
    (exposure)
    (film_deposition)
    (impurities_implantation)
    (resist_coating)
    (resist_stripping)
    (startsymb)
    (f_copy)
    (f_sync)
    (f_world)
    (f_ok)
    (f_goal)
    (q_1)
    (q_1s)
    (q_1t)
    (q_2)
    (q_2s)
    (q_2t)
    (q_3)
    (q_3s)
    (q_3t)
    (q_4)
    (q_4s)
    (q_4t)
    (q_5)
    (q_5s)
    (q_5t)
    (q_6)
    (q_6s)
    (q_6t)
    (q_7)
    (q_7s)
    (q_7t)
    (q_8)
    (q_8s)
    (q_8t)
    (q_9)
    (q_9s)
    (q_9t)
    (q_10)
    (q_10s)
    (q_10t)
    (q_11)
    (q_11s)
    (q_11t)
    (q_12)
    (q_12s)
    (q_12t)
    (q_13)
    (q_13s)
    (q_13t)
    (q_14)
    (q_14s)
    (q_14t)
    (q_15)
    (q_15s)
    (q_15t)
    (q_16)
    (q_16s)
    (q_16t)
    (q_17)
    (q_17s)
    (q_17t)
    (q_18)
    (q_18s)
    (q_18t)
    (q_19)
    (q_19s)
    (q_19t)
    (q_20)
    (q_20s)
    (q_20t)
    (q_21)
    (q_21s)
    (q_21t)
    (q_22)
    (q_22s)
    (q_22t)
    (q_23)
    (q_23s)
    (q_23t)
    (q_24)
    (q_24s)
    (q_24t)
    (q_25)
    (q_25s)
    (q_25t)
    (q_26)
    (q_26s)
    (q_26t)
    (q_27)
    (q_27s)
    (q_27t)
    (q_28)
    (q_28s)
    (q_28t)
    (q_29)
    (q_29s)
    (q_29t)
    (q_30)
    (q_30s)
    (q_30t)
    (q_31)
    (q_31s)
    (q_31t)
    (q_32)
    (q_32s)
    (q_32t)
    (q_33)
    (q_33s)
    (q_33t)
    (q_34)
    (q_34s)
    (q_34t)
    (q_35)
    (q_35s)
    (q_35t)
    (q_36)
    (q_36s)
    (q_36t)
    (q_37)
    (q_37s)
    (q_37t)
    (q_38)
    (q_38s)
    (q_38t)
    (q_39)
    (q_39s)
    (q_39t)
    (q_40)
    (q_40s)
    (q_40t)
    (q_41)
    (q_41s)
    (q_41t)
    (q_42)
    (q_42s)
    (q_42t)
    (q_43)
    (q_43s)
    (q_43t)
    (q_44)
    (q_44s)
    (q_44t)
    (q_45)
    (q_45s)
    (q_45t)
    (q_46)
    (q_46s)
    (q_46t)
    (q_47)
    (q_47s)
    (q_47t)
    (q_48)
    (q_48s)
    (q_48t)
    (q_49)
    (q_49s)
    (q_49t)
    (q_50)
    (q_50s)
    (q_50t)
    (q_51)
    (q_51s)
    (q_51t)
    (q_52)
    (q_52s)
    (q_52t)
    (q_53)
    (q_53s)
    (q_53t)
    (q_54)
    (q_54s)
    (q_54t)
    (q_55)
    (q_55s)
    (q_55t)
    (q_56)
    (q_56s)
    (q_56t)
    (q_57)
    (q_57s)
    (q_57t)
    (q_58)
    (q_58s)
    (q_58t)
    (q_59)
    (q_59s)
    (q_59t)
    (q_60)
    (q_60s)
    (q_60t)
    (q_61)
    (q_61s)
    (q_61t)
    (q_62)
    (q_62s)
    (q_62t)
    (q_63)
    (q_63s)
    (q_63t)
    (q_64)
    (q_64s)
    (q_64t)
    (q_65)
    (q_65s)
    (q_65t)
    (q_66)
    (q_66s)
    (q_66t)
    (q_67)
    (q_67s)
    (q_67t)
    (q_68)
    (q_68s)
    (q_68t)
    (q_69)
    (q_69s)
    (q_69t)
    (q_70)
    (q_70s)
    (q_70t)
    (q_71)
    (q_71s)
    (q_71t)
    (q_72)
    (q_72s)
    (q_72t)
    (q_73)
    (q_73s)
    (q_73t)
    (q_74)
    (q_74s)
    (q_74t)
    (q_75)
    (q_75s)
    (q_75t)
    (q_76)
    (q_76s)
    (q_76t)
    (q_77)
    (q_77s)
    (q_77t)
    (q_78)
    (q_78s)
    (q_78t)
    (q_79)
    (q_79s)
    (q_79t)
    (q_80)
    (q_80s)
    (q_80t)
    (q_81)
    (q_81s)
    (q_81t)
    (q_82)
    (q_82s)
    (q_82t)
    (q_83)
    (q_83s)
    (q_83t)
    (q_84)
    (q_84s)
    (q_84t)
    (q_85)
    (q_85s)
    (q_85t)
    (q_86)
    (q_86s)
    (q_86t)
    (q_87)
    (q_87s)
    (q_87t)
    (q_88)
    (q_88s)
    (q_88t)
    (q_89)
    (q_89s)
    (q_89t)
    (q_90)
    (q_90s)
    (q_90t)
    (q_91)
    (q_91s)
    (q_91t)
    (q_92)
    (q_92s)
    (q_92t)
    (q_93)
    (q_93s)
    (q_93t)
    (q_94)
    (q_94s)
    (q_94t)
    (q_95)
    (q_95s)
    (q_95t)
    (q_96)
    (q_96s)
    (q_96t)
    (q_97)
    (q_97s)
    (q_97t)
    (q_98)
    (q_98s)
    (q_98t)
    (q_99)
    (q_99s)
    (q_99t)
    (q_100)
    (q_100s)
    (q_100t)
    (q_101)
    (q_101s)
    (q_101t)
    (q_102)
    (q_102s)
    (q_102t)
    (q_103)
    (q_103s)
    (q_103t)
    (q_104)
    (q_104s)
    (q_104t)
    (q_105)
    (q_105s)
    (q_105t)
    (q_106)
    (q_106s)
    (q_106t)
    (q_107)
    (q_107s)
    (q_107t)
    (q_108)
    (q_108s)
    (q_108t)
    (q_109)
    (q_109s)
    (q_109t)
    (q_110)
    (q_110s)
    (q_110t)
    (q_111)
    (q_111s)
    (q_111t)
    (q_112)
    (q_112s)
    (q_112t)
  )
  (:action activation_7_handler_activation_0
    :parameters ()
    :precondition 
      (and
        (current_state_7 s7_handler_activation_0)
        (f_ok)
        (f_world))
    :effect
      (and
        (current_state_7 s7_handler_activation_0)
        (activation)
        (f_copy)
        (not 
          (cleaning))
        (not 
          (development))
        (not 
          (etching))
        (not 
          (exposure))
        (not 
          (film_deposition))
        (not 
          (impurities_implantation))
        (not 
          (resist_coating))
        (not 
          (resist_stripping))
        (not 
          (f_world))
      )
    )
  (:action cleaning_0_handler_cleaning_0
    :parameters ()
    :precondition 
      (and
        (current_state_0 s0_handler_cleaning_0)
        (f_ok)
        (f_world))
    :effect
      (and
        (current_state_0 s0_handler_cleaning_0)
        (cleaning)
        (f_copy)
        (not 
          (activation))
        (not 
          (development))
        (not 
          (etching))
        (not 
          (exposure))
        (not 
          (film_deposition))
        (not 
          (impurities_implantation))
        (not 
          (resist_coating))
        (not 
          (resist_stripping))
        (not 
          (f_world))
      )
    )
  (:action development_4_handler_development_0
    :parameters ()
    :precondition 
      (and
        (current_state_4 s4_handler_development_0)
        (f_ok)
        (f_world))
    :effect
      (and
        (current_state_4 s4_handler_development_0)
        (development)
        (f_copy)
        (not 
          (activation))
        (not 
          (cleaning))
        (not 
          (etching))
        (not 
          (exposure))
        (not 
          (film_deposition))
        (not 
          (impurities_implantation))
        (not 
          (resist_coating))
        (not 
          (resist_stripping))
        (not 
          (f_world))
      )
    )
  (:action etching_5_handler_etching_0
    :parameters ()
    :precondition 
      (and
        (current_state_5 s5_handler_etching_0)
        (f_ok)
        (f_world))
    :effect
      (and
        (current_state_5 s5_handler_etching_0)
        (etching)
        (f_copy)
        (not 
          (activation))
        (not 
          (cleaning))
        (not 
          (development))
        (not 
          (exposure))
        (not 
          (film_deposition))
        (not 
          (impurities_implantation))
        (not 
          (resist_coating))
        (not 
          (resist_stripping))
        (not 
          (f_world))
      )
    )
  (:action exposure_3_handler_exposure_0
    :parameters ()
    :precondition 
      (and
        (current_state_3 s3_handler_exposure_0)
        (f_ok)
        (f_world))
    :effect
      (and
        (current_state_3 s3_handler_exposure_0)
        (exposure)
        (f_copy)
        (not 
          (activation))
        (not 
          (cleaning))
        (not 
          (development))
        (not 
          (etching))
        (not 
          (film_deposition))
        (not 
          (impurities_implantation))
        (not 
          (resist_coating))
        (not 
          (resist_stripping))
        (not 
          (f_world))
      )
    )
  (:action film_deposition_1_handler_film_deposition_0
    :parameters ()
    :precondition 
      (and
        (current_state_1 s1_handler_film_deposition_0)
        (f_ok)
        (f_world))
    :effect
      (and
        (current_state_1 s1_handler_film_deposition_0)
        (film_deposition)
        (f_copy)
        (not 
          (activation))
        (not 
          (cleaning))
        (not 
          (development))
        (not 
          (etching))
        (not 
          (exposure))
        (not 
          (impurities_implantation))
        (not 
          (resist_coating))
        (not 
          (resist_stripping))
        (not 
          (f_world))
      )
    )
  (:action impurities_implantation_6_handler_impurities_implantation_0
    :parameters ()
    :precondition 
      (and
        (current_state_6 s6_handler_impurities_implantation_0)
        (f_ok)
        (f_world))
    :effect
      (and
        (current_state_6 s6_handler_impurities_implantation_0)
        (impurities_implantation)
        (f_copy)
        (not 
          (activation))
        (not 
          (cleaning))
        (not 
          (development))
        (not 
          (etching))
        (not 
          (exposure))
        (not 
          (film_deposition))
        (not 
          (resist_coating))
        (not 
          (resist_stripping))
        (not 
          (f_world))
      )
    )
  (:action resist_coating_2_handler_resist_coating_0
    :parameters ()
    :precondition 
      (and
        (current_state_2 s2_handler_resist_coating_0)
        (f_ok)
        (f_world))
    :effect
      (and
        (current_state_2 s2_handler_resist_coating_0)
        (resist_coating)
        (f_copy)
        (not 
          (activation))
        (not 
          (cleaning))
        (not 
          (development))
        (not 
          (etching))
        (not 
          (exposure))
        (not 
          (film_deposition))
        (not 
          (impurities_implantation))
        (not 
          (resist_stripping))
        (not 
          (f_world))
      )
    )
  (:action resist_stripping_8_handler_resist_stripping_0
    :parameters ()
    :precondition 
      (and
        (current_state_8 s8_handler_resist_stripping_0)
        (f_ok)
        (f_world))
    :effect
      (and
        (oneof (current_state_8 s8_handler_resist_stripping_0) (and (not (current_state_8 s8_handler_resist_stripping_0)) (current_state_8 s8_handler_resist_stripping_broken)))
        (resist_stripping)
        (f_copy)
        (not 
          (activation))
        (not 
          (cleaning))
        (not 
          (development))
        (not 
          (etching))
        (not 
          (exposure))
        (not 
          (film_deposition))
        (not 
          (impurities_implantation))
        (not 
          (resist_coating))
        (not 
          (f_world))
      )
    )
  (:action o_copy
    :parameters ()
    :precondition 
      (and
        (f_ok)
        (f_copy))
    :effect
      (and
        (f_sync)
        (q_1t)
        (when
          (q_1)
          (q_1s))
        (when
          (q_2)
          (q_2s))
        (when
          (q_3)
          (q_3s))
        (when
          (q_4)
          (q_4s))
        (when
          (q_5)
          (q_5s))
        (when
          (q_6)
          (q_6s))
        (when
          (q_7)
          (q_7s))
        (when
          (q_8)
          (q_8s))
        (when
          (q_9)
          (q_9s))
        (when
          (q_10)
          (q_10s))
        (when
          (q_11)
          (q_11s))
        (when
          (q_12)
          (q_12s))
        (when
          (q_13)
          (q_13s))
        (when
          (q_14)
          (q_14s))
        (when
          (q_15)
          (q_15s))
        (when
          (q_16)
          (q_16s))
        (when
          (q_17)
          (q_17s))
        (when
          (q_18)
          (q_18s))
        (when
          (q_19)
          (q_19s))
        (when
          (q_20)
          (q_20s))
        (when
          (q_21)
          (q_21s))
        (when
          (q_22)
          (q_22s))
        (when
          (q_23)
          (q_23s))
        (when
          (q_24)
          (q_24s))
        (when
          (q_25)
          (q_25s))
        (when
          (q_26)
          (q_26s))
        (when
          (q_27)
          (q_27s))
        (when
          (q_28)
          (q_28s))
        (when
          (q_29)
          (q_29s))
        (when
          (q_30)
          (q_30s))
        (when
          (q_31)
          (q_31s))
        (when
          (q_32)
          (q_32s))
        (when
          (q_33)
          (q_33s))
        (when
          (q_34)
          (q_34s))
        (when
          (q_35)
          (q_35s))
        (when
          (q_36)
          (q_36s))
        (when
          (q_37)
          (q_37s))
        (when
          (q_38)
          (q_38s))
        (when
          (q_39)
          (q_39s))
        (when
          (q_40)
          (q_40s))
        (when
          (q_41)
          (q_41s))
        (when
          (q_42)
          (q_42s))
        (when
          (q_43)
          (q_43s))
        (when
          (q_44)
          (q_44s))
        (when
          (q_45)
          (q_45s))
        (when
          (q_46)
          (q_46s))
        (when
          (q_47)
          (q_47s))
        (when
          (q_48)
          (q_48s))
        (when
          (q_49)
          (q_49s))
        (when
          (q_50)
          (q_50s))
        (when
          (q_51)
          (q_51s))
        (when
          (q_52)
          (q_52s))
        (when
          (q_53)
          (q_53s))
        (when
          (q_54)
          (q_54s))
        (when
          (q_55)
          (q_55s))
        (when
          (q_56)
          (q_56s))
        (when
          (q_57)
          (q_57s))
        (when
          (q_58)
          (q_58s))
        (when
          (q_59)
          (q_59s))
        (when
          (q_60)
          (q_60s))
        (when
          (q_61)
          (q_61s))
        (when
          (q_62)
          (q_62s))
        (when
          (q_63)
          (q_63s))
        (when
          (q_64)
          (q_64s))
        (when
          (q_65)
          (q_65s))
        (when
          (q_66)
          (q_66s))
        (when
          (q_67)
          (q_67s))
        (when
          (q_68)
          (q_68s))
        (when
          (q_69)
          (q_69s))
        (when
          (q_70)
          (q_70s))
        (when
          (q_71)
          (q_71s))
        (when
          (q_72)
          (q_72s))
        (when
          (q_73)
          (q_73s))
        (when
          (q_74)
          (q_74s))
        (when
          (q_75)
          (q_75s))
        (when
          (q_76)
          (q_76s))
        (when
          (q_77)
          (q_77s))
        (when
          (q_78)
          (q_78s))
        (when
          (q_79)
          (q_79s))
        (when
          (q_80)
          (q_80s))
        (when
          (q_81)
          (q_81s))
        (when
          (q_82)
          (q_82s))
        (when
          (q_83)
          (q_83s))
        (when
          (q_84)
          (q_84s))
        (when
          (q_85)
          (q_85s))
        (when
          (q_86)
          (q_86s))
        (when
          (q_87)
          (q_87s))
        (when
          (q_88)
          (q_88s))
        (when
          (q_89)
          (q_89s))
        (when
          (q_90)
          (q_90s))
        (when
          (q_91)
          (q_91s))
        (when
          (q_92)
          (q_92s))
        (when
          (q_93)
          (q_93s))
        (when
          (q_94)
          (q_94s))
        (when
          (q_95)
          (q_95s))
        (when
          (q_96)
          (q_96s))
        (when
          (q_97)
          (q_97s))
        (when
          (q_98)
          (q_98s))
        (when
          (q_99)
          (q_99s))
        (when
          (q_100)
          (q_100s))
        (when
          (q_101)
          (q_101s))
        (when
          (q_102)
          (q_102s))
        (when
          (q_103)
          (q_103s))
        (when
          (q_104)
          (q_104s))
        (when
          (q_105)
          (q_105s))
        (when
          (q_106)
          (q_106s))
        (when
          (q_107)
          (q_107s))
        (when
          (q_108)
          (q_108s))
        (when
          (q_109)
          (q_109s))
        (when
          (q_110)
          (q_110s))
        (when
          (q_111)
          (q_111s))
        (when
          (q_112)
          (q_112s))
        (not 
          (f_copy))
        (not 
          (q_1))
        (not 
          (q_2))
        (not 
          (q_3))
        (not 
          (q_4))
        (not 
          (q_5))
        (not 
          (q_6))
        (not 
          (q_7))
        (not 
          (q_8))
        (not 
          (q_9))
        (not 
          (q_10))
        (not 
          (q_11))
        (not 
          (q_12))
        (not 
          (q_13))
        (not 
          (q_14))
        (not 
          (q_15))
        (not 
          (q_16))
        (not 
          (q_17))
        (not 
          (q_18))
        (not 
          (q_19))
        (not 
          (q_20))
        (not 
          (q_21))
        (not 
          (q_22))
        (not 
          (q_23))
        (not 
          (q_24))
        (not 
          (q_25))
        (not 
          (q_26))
        (not 
          (q_27))
        (not 
          (q_28))
        (not 
          (q_29))
        (not 
          (q_30))
        (not 
          (q_31))
        (not 
          (q_32))
        (not 
          (q_33))
        (not 
          (q_34))
        (not 
          (q_35))
        (not 
          (q_36))
        (not 
          (q_37))
        (not 
          (q_38))
        (not 
          (q_39))
        (not 
          (q_40))
        (not 
          (q_41))
        (not 
          (q_42))
        (not 
          (q_43))
        (not 
          (q_44))
        (not 
          (q_45))
        (not 
          (q_46))
        (not 
          (q_47))
        (not 
          (q_48))
        (not 
          (q_49))
        (not 
          (q_50))
        (not 
          (q_51))
        (not 
          (q_52))
        (not 
          (q_53))
        (not 
          (q_54))
        (not 
          (q_55))
        (not 
          (q_56))
        (not 
          (q_57))
        (not 
          (q_58))
        (not 
          (q_59))
        (not 
          (q_60))
        (not 
          (q_61))
        (not 
          (q_62))
        (not 
          (q_63))
        (not 
          (q_64))
        (not 
          (q_65))
        (not 
          (q_66))
        (not 
          (q_67))
        (not 
          (q_68))
        (not 
          (q_69))
        (not 
          (q_70))
        (not 
          (q_71))
        (not 
          (q_72))
        (not 
          (q_73))
        (not 
          (q_74))
        (not 
          (q_75))
        (not 
          (q_76))
        (not 
          (q_77))
        (not 
          (q_78))
        (not 
          (q_79))
        (not 
          (q_80))
        (not 
          (q_81))
        (not 
          (q_82))
        (not 
          (q_83))
        (not 
          (q_84))
        (not 
          (q_85))
        (not 
          (q_86))
        (not 
          (q_87))
        (not 
          (q_88))
        (not 
          (q_89))
        (not 
          (q_90))
        (not 
          (q_91))
        (not 
          (q_92))
        (not 
          (q_93))
        (not 
          (q_94))
        (not 
          (q_95))
        (not 
          (q_96))
        (not 
          (q_97))
        (not 
          (q_98))
        (not 
          (q_99))
        (not 
          (q_100))
        (not 
          (q_101))
        (not 
          (q_102))
        (not 
          (q_103))
        (not 
          (q_104))
        (not 
          (q_105))
        (not 
          (q_106))
        (not 
          (q_107))
        (not 
          (q_108))
        (not 
          (q_109))
        (not 
          (q_110))
        (not 
          (q_111))
        (not 
          (q_112))
      )
    )
  (:action o_goal
    :parameters ()
    :precondition 
      (and
        (f_world)
        (f_ok)
        (not 
          (q_1))
        (not 
          (q_2))
        (not 
          (q_3))
        (not 
          (q_4))
        (not 
          (q_5))
        (not 
          (q_6))
        (not 
          (q_7))
        (not 
          (q_8))
        (not 
          (q_9))
        (not 
          (q_10))
        (not 
          (q_11))
        (not 
          (q_12))
        (not 
          (q_13))
        (not 
          (q_14))
        (not 
          (q_15))
        (not 
          (q_16))
        (not 
          (q_17))
        (not 
          (q_18))
        (not 
          (q_19))
        (not 
          (q_20))
        (not 
          (q_21))
        (not 
          (q_22))
        (not 
          (q_23))
        (not 
          (q_24))
        (not 
          (q_25))
        (not 
          (q_26))
        (not 
          (q_27))
        (not 
          (q_28))
        (not 
          (q_29))
        (not 
          (q_30))
        (not 
          (q_31))
        (not 
          (q_32))
        (not 
          (q_33))
        (not 
          (q_34))
        (not 
          (q_35))
        (not 
          (q_36))
        (not 
          (q_37))
        (not 
          (q_38))
        (not 
          (q_39))
        (not 
          (q_40))
        (not 
          (q_41))
        (not 
          (q_42))
        (not 
          (q_43))
        (not 
          (q_44))
        (not 
          (q_45))
        (not 
          (q_46))
        (not 
          (q_47))
        (not 
          (q_48))
        (not 
          (q_49))
        (not 
          (q_50))
        (not 
          (q_51))
        (not 
          (q_52))
        (not 
          (q_53))
        (not 
          (q_54))
        (not 
          (q_55))
        (not 
          (q_56))
        (not 
          (q_57))
        (not 
          (q_58))
        (not 
          (q_59))
        (not 
          (q_60))
        (not 
          (q_61))
        (not 
          (q_62))
        (not 
          (q_63))
        (not 
          (q_64))
        (not 
          (q_65))
        (not 
          (q_66))
        (not 
          (q_67))
        (not 
          (q_68))
        (not 
          (q_69))
        (not 
          (q_70))
        (not 
          (q_71))
        (not 
          (q_72))
        (not 
          (q_73))
        (not 
          (q_74))
        (not 
          (q_75))
        (not 
          (q_76))
        (not 
          (q_77))
        (not 
          (q_78))
        (not 
          (q_79))
        (not 
          (q_80))
        (not 
          (q_81))
        (not 
          (q_82))
        (not 
          (q_83))
        (not 
          (q_84))
        (not 
          (q_85))
        (not 
          (q_86))
        (not 
          (q_87))
        (not 
          (q_88))
        (not 
          (q_89))
        (not 
          (q_90))
        (not 
          (q_91))
        (not 
          (q_92))
        (not 
          (q_93))
        (not 
          (q_94))
        (not 
          (q_95))
        (not 
          (q_96))
        (not 
          (q_97))
        (not 
          (q_98))
        (not 
          (q_99))
        (not 
          (q_100))
        (not 
          (q_101))
        (not 
          (q_102))
        (not 
          (q_103))
        (not 
          (q_104))
        (not 
          (q_105))
        (not 
          (q_106))
        (not 
          (q_107))
        (not 
          (q_108))
        (not 
          (q_109))
        (not 
          (q_110))
        (not 
          (q_111)))
    :effect
(f_goal)    )
  (:action o_sync_q_1s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_1t))
    :effect
      (and
        (when
          (q_1s)
          (q_101s))
        (when
          (q_1s)
          (q_2s))
        (q_2t)
        (when
          (q_1s)
          (not 
            (q_1s)))
        (not 
          (q_1t))
      )
    )
  (:action o_sync_q_2s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_2t))
    :effect
      (and
        (when
          (q_2s)
          (q_111))
        (when
          (q_2s)
          (q_3))
        (q_3t)
        (when
          (q_2s)
          (not 
            (q_2s)))
        (not 
          (q_2t))
      )
    )
  (:action o_sync_q_3s_1
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_3t))
    :effect
      (and
        (when
          (q_3s)
          (q_4s))
        (q_4t)
        (when
          (q_3s)
          (not 
            (q_3s)))
        (not 
          (q_3t))
      )
    )
  (:action o_sync_q_3s_2
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_3t))
    :effect
      (and
        (when
          (q_3s)
          (q_111))
        (when
          (q_3s)
          (q_3))
        (q_4t)
        (when
          (q_3s)
          (not 
            (q_3s)))
        (not 
          (q_3t))
      )
    )
  (:action o_sync_q_4s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_4t))
    :effect
      (and
        (when
          (q_4s)
          (q_109s))
        (when
          (q_4s)
          (q_5s))
        (q_5t)
        (when
          (q_4s)
          (not 
            (q_4s)))
        (not 
          (q_4t))
      )
    )
  (:action o_sync_q_5s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_5t))
    :effect
      (and
        (when
          (q_5s)
          (q_95s))
        (when
          (q_5s)
          (q_6s))
        (q_6t)
        (when
          (q_5s)
          (not 
            (q_5s)))
        (not 
          (q_5t))
      )
    )
  (:action o_sync_q_6s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_6t))
    :effect
      (and
        (when
          (q_6s)
          (q_93s))
        (when
          (q_6s)
          (q_7s))
        (q_7t)
        (when
          (q_6s)
          (not 
            (q_6s)))
        (not 
          (q_6t))
      )
    )
  (:action o_sync_q_7s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_7t))
    :effect
      (and
        (when
          (q_7s)
          (q_96s))
        (when
          (q_7s)
          (q_8s))
        (q_8t)
        (when
          (q_7s)
          (not 
            (q_7s)))
        (not 
          (q_7t))
      )
    )
  (:action o_sync_q_8s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_8t))
    :effect
      (and
        (when
          (q_8s)
          (q_98s))
        (when
          (q_8s)
          (q_9s))
        (q_9t)
        (when
          (q_8s)
          (not 
            (q_8s)))
        (not 
          (q_8t))
      )
    )
  (:action o_sync_q_9s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_9t))
    :effect
      (and
        (when
          (q_9s)
          (q_97s))
        (when
          (q_9s)
          (q_10s))
        (q_10t)
        (when
          (q_9s)
          (not 
            (q_9s)))
        (not 
          (q_9t))
      )
    )
  (:action o_sync_q_10s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_10t))
    :effect
      (and
        (when
          (q_10s)
          (q_94s))
        (when
          (q_10s)
          (q_11s))
        (q_11t)
        (when
          (q_10s)
          (not 
            (q_10s)))
        (not 
          (q_10t))
      )
    )
  (:action o_sync_q_11s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_11t))
    :effect
      (and
        (when
          (q_11s)
          (q_100s))
        (when
          (q_11s)
          (q_12s))
        (q_12t)
        (when
          (q_11s)
          (not 
            (q_11s)))
        (not 
          (q_11t))
      )
    )
  (:action o_sync_q_12s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_12t))
    :effect
      (and
        (when
          (q_12s)
          (q_13s))
        (when
          (q_12s)
          (q_92s))
        (q_13t)
        (when
          (q_12s)
          (not 
            (q_12s)))
        (not 
          (q_12t))
      )
    )
  (:action o_sync_q_13s_1
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_13t))
    :effect
      (and
        (when
          (q_13s)
          (q_14s))
        (q_14t)
        (when
          (q_13s)
          (not 
            (q_13s)))
        (not 
          (q_13t))
      )
    )
  (:action o_sync_q_13s_2
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_13t))
    :effect
      (and
        (when
          (q_13s)
          (q_111))
        (when
          (q_13s)
          (q_13))
        (q_14t)
        (when
          (q_13s)
          (not 
            (q_13s)))
        (not 
          (q_13t))
      )
    )
  (:action o_sync_q_14s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_14t))
    :effect
      (and
        (when
          (q_14s)
          (q_105s))
        (when
          (q_14s)
          (q_15s))
        (q_15t)
        (when
          (q_14s)
          (not 
            (q_14s)))
        (not 
          (q_14t))
      )
    )
  (:action o_sync_q_15s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_15t))
    :effect
      (and
        (when
          (q_15s)
          (q_99s))
        (when
          (q_15s)
          (q_16s))
        (q_16t)
        (when
          (q_15s)
          (not 
            (q_15s)))
        (not 
          (q_15t))
      )
    )
  (:action o_sync_q_16s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_16t))
    :effect
      (and
        (when
          (q_16s)
          (q_93s))
        (when
          (q_16s)
          (q_17s))
        (q_17t)
        (when
          (q_16s)
          (not 
            (q_16s)))
        (not 
          (q_16t))
      )
    )
  (:action o_sync_q_17s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_17t))
    :effect
      (and
        (when
          (q_17s)
          (q_96s))
        (when
          (q_17s)
          (q_18s))
        (q_18t)
        (when
          (q_17s)
          (not 
            (q_17s)))
        (not 
          (q_17t))
      )
    )
  (:action o_sync_q_18s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_18t))
    :effect
      (and
        (when
          (q_18s)
          (q_98s))
        (when
          (q_18s)
          (q_19s))
        (q_19t)
        (when
          (q_18s)
          (not 
            (q_18s)))
        (not 
          (q_18t))
      )
    )
  (:action o_sync_q_19s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_19t))
    :effect
      (and
        (when
          (q_19s)
          (q_97s))
        (when
          (q_19s)
          (q_20s))
        (q_20t)
        (when
          (q_19s)
          (not 
            (q_19s)))
        (not 
          (q_19t))
      )
    )
  (:action o_sync_q_20s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_20t))
    :effect
      (and
        (when
          (q_20s)
          (q_94s))
        (when
          (q_20s)
          (q_21s))
        (q_21t)
        (when
          (q_20s)
          (not 
            (q_20s)))
        (not 
          (q_20t))
      )
    )
  (:action o_sync_q_21s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_21t))
    :effect
      (and
        (when
          (q_21s)
          (q_100s))
        (when
          (q_21s)
          (q_22s))
        (q_22t)
        (when
          (q_21s)
          (not 
            (q_21s)))
        (not 
          (q_21t))
      )
    )
  (:action o_sync_q_22s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_22t))
    :effect
      (and
        (when
          (q_22s)
          (q_23s))
        (when
          (q_22s)
          (q_92s))
        (q_23t)
        (when
          (q_22s)
          (not 
            (q_22s)))
        (not 
          (q_22t))
      )
    )
  (:action o_sync_q_23s_1
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_23t))
    :effect
      (and
        (when
          (q_23s)
          (q_24s))
        (q_24t)
        (when
          (q_23s)
          (not 
            (q_23s)))
        (not 
          (q_23t))
      )
    )
  (:action o_sync_q_23s_2
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_23t))
    :effect
      (and
        (when
          (q_23s)
          (q_111))
        (when
          (q_23s)
          (q_23))
        (q_24t)
        (when
          (q_23s)
          (not 
            (q_23s)))
        (not 
          (q_23t))
      )
    )
  (:action o_sync_q_24s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_24t))
    :effect
      (and
        (when
          (q_24s)
          (q_103s))
        (when
          (q_24s)
          (q_25s))
        (q_25t)
        (when
          (q_24s)
          (not 
            (q_24s)))
        (not 
          (q_24t))
      )
    )
  (:action o_sync_q_25s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_25t))
    :effect
      (and
        (when
          (q_25s)
          (q_99s))
        (when
          (q_25s)
          (q_26s))
        (q_26t)
        (when
          (q_25s)
          (not 
            (q_25s)))
        (not 
          (q_25t))
      )
    )
  (:action o_sync_q_26s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_26t))
    :effect
      (and
        (when
          (q_26s)
          (q_95s))
        (when
          (q_26s)
          (q_27s))
        (q_27t)
        (when
          (q_26s)
          (not 
            (q_26s)))
        (not 
          (q_26t))
      )
    )
  (:action o_sync_q_27s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_27t))
    :effect
      (and
        (when
          (q_27s)
          (q_96s))
        (when
          (q_27s)
          (q_28s))
        (q_28t)
        (when
          (q_27s)
          (not 
            (q_27s)))
        (not 
          (q_27t))
      )
    )
  (:action o_sync_q_28s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_28t))
    :effect
      (and
        (when
          (q_28s)
          (q_98s))
        (when
          (q_28s)
          (q_29s))
        (q_29t)
        (when
          (q_28s)
          (not 
            (q_28s)))
        (not 
          (q_28t))
      )
    )
  (:action o_sync_q_29s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_29t))
    :effect
      (and
        (when
          (q_29s)
          (q_97s))
        (when
          (q_29s)
          (q_30s))
        (q_30t)
        (when
          (q_29s)
          (not 
            (q_29s)))
        (not 
          (q_29t))
      )
    )
  (:action o_sync_q_30s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_30t))
    :effect
      (and
        (when
          (q_30s)
          (q_94s))
        (when
          (q_30s)
          (q_31s))
        (q_31t)
        (when
          (q_30s)
          (not 
            (q_30s)))
        (not 
          (q_30t))
      )
    )
  (:action o_sync_q_31s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_31t))
    :effect
      (and
        (when
          (q_31s)
          (q_100s))
        (when
          (q_31s)
          (q_32s))
        (q_32t)
        (when
          (q_31s)
          (not 
            (q_31s)))
        (not 
          (q_31t))
      )
    )
  (:action o_sync_q_32s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_32t))
    :effect
      (and
        (when
          (q_32s)
          (q_33s))
        (when
          (q_32s)
          (q_92s))
        (q_33t)
        (when
          (q_32s)
          (not 
            (q_32s)))
        (not 
          (q_32t))
      )
    )
  (:action o_sync_q_33s_1
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_33t))
    :effect
      (and
        (when
          (q_33s)
          (q_34s))
        (q_34t)
        (when
          (q_33s)
          (not 
            (q_33s)))
        (not 
          (q_33t))
      )
    )
  (:action o_sync_q_33s_2
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_33t))
    :effect
      (and
        (when
          (q_33s)
          (q_111))
        (when
          (q_33s)
          (q_33))
        (q_34t)
        (when
          (q_33s)
          (not 
            (q_33s)))
        (not 
          (q_33t))
      )
    )
  (:action o_sync_q_34s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_34t))
    :effect
      (and
        (when
          (q_34s)
          (q_106s))
        (when
          (q_34s)
          (q_35s))
        (q_35t)
        (when
          (q_34s)
          (not 
            (q_34s)))
        (not 
          (q_34t))
      )
    )
  (:action o_sync_q_35s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_35t))
    :effect
      (and
        (when
          (q_35s)
          (q_99s))
        (when
          (q_35s)
          (q_36s))
        (q_36t)
        (when
          (q_35s)
          (not 
            (q_35s)))
        (not 
          (q_35t))
      )
    )
  (:action o_sync_q_36s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_36t))
    :effect
      (and
        (when
          (q_36s)
          (q_95s))
        (when
          (q_36s)
          (q_37s))
        (q_37t)
        (when
          (q_36s)
          (not 
            (q_36s)))
        (not 
          (q_36t))
      )
    )
  (:action o_sync_q_37s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_37t))
    :effect
      (and
        (when
          (q_37s)
          (q_93s))
        (when
          (q_37s)
          (q_38s))
        (q_38t)
        (when
          (q_37s)
          (not 
            (q_37s)))
        (not 
          (q_37t))
      )
    )
  (:action o_sync_q_38s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_38t))
    :effect
      (and
        (when
          (q_38s)
          (q_98s))
        (when
          (q_38s)
          (q_39s))
        (q_39t)
        (when
          (q_38s)
          (not 
            (q_38s)))
        (not 
          (q_38t))
      )
    )
  (:action o_sync_q_39s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_39t))
    :effect
      (and
        (when
          (q_39s)
          (q_97s))
        (when
          (q_39s)
          (q_40s))
        (q_40t)
        (when
          (q_39s)
          (not 
            (q_39s)))
        (not 
          (q_39t))
      )
    )
  (:action o_sync_q_40s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_40t))
    :effect
      (and
        (when
          (q_40s)
          (q_94s))
        (when
          (q_40s)
          (q_41s))
        (q_41t)
        (when
          (q_40s)
          (not 
            (q_40s)))
        (not 
          (q_40t))
      )
    )
  (:action o_sync_q_41s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_41t))
    :effect
      (and
        (when
          (q_41s)
          (q_100s))
        (when
          (q_41s)
          (q_42s))
        (q_42t)
        (when
          (q_41s)
          (not 
            (q_41s)))
        (not 
          (q_41t))
      )
    )
  (:action o_sync_q_42s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_42t))
    :effect
      (and
        (when
          (q_42s)
          (q_43s))
        (when
          (q_42s)
          (q_92s))
        (q_43t)
        (when
          (q_42s)
          (not 
            (q_42s)))
        (not 
          (q_42t))
      )
    )
  (:action o_sync_q_43s_1
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_43t))
    :effect
      (and
        (when
          (q_43s)
          (q_44s))
        (q_44t)
        (when
          (q_43s)
          (not 
            (q_43s)))
        (not 
          (q_43t))
      )
    )
  (:action o_sync_q_43s_2
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_43t))
    :effect
      (and
        (when
          (q_43s)
          (q_111))
        (when
          (q_43s)
          (q_43))
        (q_44t)
        (when
          (q_43s)
          (not 
            (q_43s)))
        (not 
          (q_43t))
      )
    )
  (:action o_sync_q_44s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_44t))
    :effect
      (and
        (when
          (q_44s)
          (q_108s))
        (when
          (q_44s)
          (q_45s))
        (q_45t)
        (when
          (q_44s)
          (not 
            (q_44s)))
        (not 
          (q_44t))
      )
    )
  (:action o_sync_q_45s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_45t))
    :effect
      (and
        (when
          (q_45s)
          (q_99s))
        (when
          (q_45s)
          (q_46s))
        (q_46t)
        (when
          (q_45s)
          (not 
            (q_45s)))
        (not 
          (q_45t))
      )
    )
  (:action o_sync_q_46s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_46t))
    :effect
      (and
        (when
          (q_46s)
          (q_95s))
        (when
          (q_46s)
          (q_47s))
        (q_47t)
        (when
          (q_46s)
          (not 
            (q_46s)))
        (not 
          (q_46t))
      )
    )
  (:action o_sync_q_47s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_47t))
    :effect
      (and
        (when
          (q_47s)
          (q_93s))
        (when
          (q_47s)
          (q_48s))
        (q_48t)
        (when
          (q_47s)
          (not 
            (q_47s)))
        (not 
          (q_47t))
      )
    )
  (:action o_sync_q_48s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_48t))
    :effect
      (and
        (when
          (q_48s)
          (q_96s))
        (when
          (q_48s)
          (q_49s))
        (q_49t)
        (when
          (q_48s)
          (not 
            (q_48s)))
        (not 
          (q_48t))
      )
    )
  (:action o_sync_q_49s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_49t))
    :effect
      (and
        (when
          (q_49s)
          (q_97s))
        (when
          (q_49s)
          (q_50s))
        (q_50t)
        (when
          (q_49s)
          (not 
            (q_49s)))
        (not 
          (q_49t))
      )
    )
  (:action o_sync_q_50s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_50t))
    :effect
      (and
        (when
          (q_50s)
          (q_94s))
        (when
          (q_50s)
          (q_51s))
        (q_51t)
        (when
          (q_50s)
          (not 
            (q_50s)))
        (not 
          (q_50t))
      )
    )
  (:action o_sync_q_51s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_51t))
    :effect
      (and
        (when
          (q_51s)
          (q_100s))
        (when
          (q_51s)
          (q_52s))
        (q_52t)
        (when
          (q_51s)
          (not 
            (q_51s)))
        (not 
          (q_51t))
      )
    )
  (:action o_sync_q_52s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_52t))
    :effect
      (and
        (when
          (q_52s)
          (q_53s))
        (when
          (q_52s)
          (q_92s))
        (q_53t)
        (when
          (q_52s)
          (not 
            (q_52s)))
        (not 
          (q_52t))
      )
    )
  (:action o_sync_q_53s_1
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_53t))
    :effect
      (and
        (when
          (q_53s)
          (q_54s))
        (q_54t)
        (when
          (q_53s)
          (not 
            (q_53s)))
        (not 
          (q_53t))
      )
    )
  (:action o_sync_q_53s_2
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_53t))
    :effect
      (and
        (when
          (q_53s)
          (q_111))
        (when
          (q_53s)
          (q_53))
        (q_54t)
        (when
          (q_53s)
          (not 
            (q_53s)))
        (not 
          (q_53t))
      )
    )
  (:action o_sync_q_54s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_54t))
    :effect
      (and
        (when
          (q_54s)
          (q_107s))
        (when
          (q_54s)
          (q_55s))
        (q_55t)
        (when
          (q_54s)
          (not 
            (q_54s)))
        (not 
          (q_54t))
      )
    )
  (:action o_sync_q_55s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_55t))
    :effect
      (and
        (when
          (q_55s)
          (q_99s))
        (when
          (q_55s)
          (q_56s))
        (q_56t)
        (when
          (q_55s)
          (not 
            (q_55s)))
        (not 
          (q_55t))
      )
    )
  (:action o_sync_q_56s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_56t))
    :effect
      (and
        (when
          (q_56s)
          (q_95s))
        (when
          (q_56s)
          (q_57s))
        (q_57t)
        (when
          (q_56s)
          (not 
            (q_56s)))
        (not 
          (q_56t))
      )
    )
  (:action o_sync_q_57s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_57t))
    :effect
      (and
        (when
          (q_57s)
          (q_93s))
        (when
          (q_57s)
          (q_58s))
        (q_58t)
        (when
          (q_57s)
          (not 
            (q_57s)))
        (not 
          (q_57t))
      )
    )
  (:action o_sync_q_58s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_58t))
    :effect
      (and
        (when
          (q_58s)
          (q_96s))
        (when
          (q_58s)
          (q_59s))
        (q_59t)
        (when
          (q_58s)
          (not 
            (q_58s)))
        (not 
          (q_58t))
      )
    )
  (:action o_sync_q_59s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_59t))
    :effect
      (and
        (when
          (q_59s)
          (q_98s))
        (when
          (q_59s)
          (q_60s))
        (q_60t)
        (when
          (q_59s)
          (not 
            (q_59s)))
        (not 
          (q_59t))
      )
    )
  (:action o_sync_q_60s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_60t))
    :effect
      (and
        (when
          (q_60s)
          (q_94s))
        (when
          (q_60s)
          (q_61s))
        (q_61t)
        (when
          (q_60s)
          (not 
            (q_60s)))
        (not 
          (q_60t))
      )
    )
  (:action o_sync_q_61s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_61t))
    :effect
      (and
        (when
          (q_61s)
          (q_100s))
        (when
          (q_61s)
          (q_62s))
        (q_62t)
        (when
          (q_61s)
          (not 
            (q_61s)))
        (not 
          (q_61t))
      )
    )
  (:action o_sync_q_62s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_62t))
    :effect
      (and
        (when
          (q_62s)
          (q_63s))
        (when
          (q_62s)
          (q_92s))
        (q_63t)
        (when
          (q_62s)
          (not 
            (q_62s)))
        (not 
          (q_62t))
      )
    )
  (:action o_sync_q_63s_1
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_63t))
    :effect
      (and
        (when
          (q_63s)
          (q_64s))
        (q_64t)
        (when
          (q_63s)
          (not 
            (q_63s)))
        (not 
          (q_63t))
      )
    )
  (:action o_sync_q_63s_2
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_63t))
    :effect
      (and
        (when
          (q_63s)
          (q_111))
        (when
          (q_63s)
          (q_63))
        (q_64t)
        (when
          (q_63s)
          (not 
            (q_63s)))
        (not 
          (q_63t))
      )
    )
  (:action o_sync_q_64s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_64t))
    :effect
      (and
        (when
          (q_64s)
          (q_104s))
        (when
          (q_64s)
          (q_65s))
        (q_65t)
        (when
          (q_64s)
          (not 
            (q_64s)))
        (not 
          (q_64t))
      )
    )
  (:action o_sync_q_65s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_65t))
    :effect
      (and
        (when
          (q_65s)
          (q_99s))
        (when
          (q_65s)
          (q_66s))
        (q_66t)
        (when
          (q_65s)
          (not 
            (q_65s)))
        (not 
          (q_65t))
      )
    )
  (:action o_sync_q_66s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_66t))
    :effect
      (and
        (when
          (q_66s)
          (q_95s))
        (when
          (q_66s)
          (q_67s))
        (q_67t)
        (when
          (q_66s)
          (not 
            (q_66s)))
        (not 
          (q_66t))
      )
    )
  (:action o_sync_q_67s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_67t))
    :effect
      (and
        (when
          (q_67s)
          (q_93s))
        (when
          (q_67s)
          (q_68s))
        (q_68t)
        (when
          (q_67s)
          (not 
            (q_67s)))
        (not 
          (q_67t))
      )
    )
  (:action o_sync_q_68s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_68t))
    :effect
      (and
        (when
          (q_68s)
          (q_96s))
        (when
          (q_68s)
          (q_69s))
        (q_69t)
        (when
          (q_68s)
          (not 
            (q_68s)))
        (not 
          (q_68t))
      )
    )
  (:action o_sync_q_69s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_69t))
    :effect
      (and
        (when
          (q_69s)
          (q_98s))
        (when
          (q_69s)
          (q_70s))
        (q_70t)
        (when
          (q_69s)
          (not 
            (q_69s)))
        (not 
          (q_69t))
      )
    )
  (:action o_sync_q_70s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_70t))
    :effect
      (and
        (when
          (q_70s)
          (q_97s))
        (when
          (q_70s)
          (q_71s))
        (q_71t)
        (when
          (q_70s)
          (not 
            (q_70s)))
        (not 
          (q_70t))
      )
    )
  (:action o_sync_q_71s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_71t))
    :effect
      (and
        (when
          (q_71s)
          (q_100s))
        (when
          (q_71s)
          (q_72s))
        (q_72t)
        (when
          (q_71s)
          (not 
            (q_71s)))
        (not 
          (q_71t))
      )
    )
  (:action o_sync_q_72s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_72t))
    :effect
      (and
        (when
          (q_72s)
          (q_73s))
        (when
          (q_72s)
          (q_92s))
        (q_73t)
        (when
          (q_72s)
          (not 
            (q_72s)))
        (not 
          (q_72t))
      )
    )
  (:action o_sync_q_73s_1
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_73t))
    :effect
      (and
        (when
          (q_73s)
          (q_74s))
        (q_74t)
        (when
          (q_73s)
          (not 
            (q_73s)))
        (not 
          (q_73t))
      )
    )
  (:action o_sync_q_73s_2
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_73t))
    :effect
      (and
        (when
          (q_73s)
          (q_111))
        (when
          (q_73s)
          (q_73))
        (q_74t)
        (when
          (q_73s)
          (not 
            (q_73s)))
        (not 
          (q_73t))
      )
    )
  (:action o_sync_q_74s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_74t))
    :effect
      (and
        (when
          (q_74s)
          (q_110s))
        (when
          (q_74s)
          (q_75s))
        (q_75t)
        (when
          (q_74s)
          (not 
            (q_74s)))
        (not 
          (q_74t))
      )
    )
  (:action o_sync_q_75s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_75t))
    :effect
      (and
        (when
          (q_75s)
          (q_99s))
        (when
          (q_75s)
          (q_76s))
        (q_76t)
        (when
          (q_75s)
          (not 
            (q_75s)))
        (not 
          (q_75t))
      )
    )
  (:action o_sync_q_76s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_76t))
    :effect
      (and
        (when
          (q_76s)
          (q_95s))
        (when
          (q_76s)
          (q_77s))
        (q_77t)
        (when
          (q_76s)
          (not 
            (q_76s)))
        (not 
          (q_76t))
      )
    )
  (:action o_sync_q_77s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_77t))
    :effect
      (and
        (when
          (q_77s)
          (q_93s))
        (when
          (q_77s)
          (q_78s))
        (q_78t)
        (when
          (q_77s)
          (not 
            (q_77s)))
        (not 
          (q_77t))
      )
    )
  (:action o_sync_q_78s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_78t))
    :effect
      (and
        (when
          (q_78s)
          (q_96s))
        (when
          (q_78s)
          (q_79s))
        (q_79t)
        (when
          (q_78s)
          (not 
            (q_78s)))
        (not 
          (q_78t))
      )
    )
  (:action o_sync_q_79s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_79t))
    :effect
      (and
        (when
          (q_79s)
          (q_98s))
        (when
          (q_79s)
          (q_80s))
        (q_80t)
        (when
          (q_79s)
          (not 
            (q_79s)))
        (not 
          (q_79t))
      )
    )
  (:action o_sync_q_80s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_80t))
    :effect
      (and
        (when
          (q_80s)
          (q_97s))
        (when
          (q_80s)
          (q_81s))
        (q_81t)
        (when
          (q_80s)
          (not 
            (q_80s)))
        (not 
          (q_80t))
      )
    )
  (:action o_sync_q_81s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_81t))
    :effect
      (and
        (when
          (q_81s)
          (q_94s))
        (when
          (q_81s)
          (q_82s))
        (q_82t)
        (when
          (q_81s)
          (not 
            (q_81s)))
        (not 
          (q_81t))
      )
    )
  (:action o_sync_q_82s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_82t))
    :effect
      (and
        (when
          (q_82s)
          (q_83s))
        (when
          (q_82s)
          (q_92s))
        (q_83t)
        (when
          (q_82s)
          (not 
            (q_82s)))
        (not 
          (q_82t))
      )
    )
  (:action o_sync_q_83s_1
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_83t))
    :effect
      (and
        (when
          (q_83s)
          (q_84s))
        (q_84t)
        (when
          (q_83s)
          (not 
            (q_83s)))
        (not 
          (q_83t))
      )
    )
  (:action o_sync_q_83s_2
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_83t))
    :effect
      (and
        (when
          (q_83s)
          (q_111))
        (when
          (q_83s)
          (q_83))
        (q_84t)
        (when
          (q_83s)
          (not 
            (q_83s)))
        (not 
          (q_83t))
      )
    )
  (:action o_sync_q_84s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_84t))
    :effect
      (and
        (when
          (q_84s)
          (q_102s))
        (when
          (q_84s)
          (q_85s))
        (q_85t)
        (when
          (q_84s)
          (not 
            (q_84s)))
        (not 
          (q_84t))
      )
    )
  (:action o_sync_q_85s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_85t))
    :effect
      (and
        (when
          (q_85s)
          (q_99s))
        (when
          (q_85s)
          (q_86s))
        (q_86t)
        (when
          (q_85s)
          (not 
            (q_85s)))
        (not 
          (q_85t))
      )
    )
  (:action o_sync_q_86s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_86t))
    :effect
      (and
        (when
          (q_86s)
          (q_95s))
        (when
          (q_86s)
          (q_87s))
        (q_87t)
        (when
          (q_86s)
          (not 
            (q_86s)))
        (not 
          (q_86t))
      )
    )
  (:action o_sync_q_87s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_87t))
    :effect
      (and
        (when
          (q_87s)
          (q_93s))
        (when
          (q_87s)
          (q_88s))
        (q_88t)
        (when
          (q_87s)
          (not 
            (q_87s)))
        (not 
          (q_87t))
      )
    )
  (:action o_sync_q_88s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_88t))
    :effect
      (and
        (when
          (q_88s)
          (q_96s))
        (when
          (q_88s)
          (q_89s))
        (q_89t)
        (when
          (q_88s)
          (not 
            (q_88s)))
        (not 
          (q_88t))
      )
    )
  (:action o_sync_q_89s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_89t))
    :effect
      (and
        (when
          (q_89s)
          (q_98s))
        (when
          (q_89s)
          (q_90s))
        (q_90t)
        (when
          (q_89s)
          (not 
            (q_89s)))
        (not 
          (q_89t))
      )
    )
  (:action o_sync_q_90s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_90t))
    :effect
      (and
        (when
          (q_90s)
          (q_97s))
        (when
          (q_90s)
          (q_91s))
        (q_91t)
        (when
          (q_90s)
          (not 
            (q_90s)))
        (not 
          (q_90t))
      )
    )
  (:action o_sync_q_91s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_91t))
    :effect
      (and
        (when
          (q_91s)
          (q_100s))
        (when
          (q_91s)
          (q_94s))
        (q_92t)
        (when
          (q_91s)
          (not 
            (q_91s)))
        (not 
          (q_91t))
      )
    )
  (:action o_sync_q_92s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_92t))
    :effect
      (and
        (q_93t)
        (when
          (q_92s)
          (not 
            (q_92s)))
        (when
          (and
            (q_92s)
            (resist_stripping))
          (not 
            (f_ok)))
        (not 
          (q_92t))
      )
    )
  (:action o_sync_q_93s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_93t))
    :effect
      (and
        (q_94t)
        (when
          (q_93s)
          (not 
            (q_93s)))
        (when
          (and
            (q_93s)
            (resist_coating))
          (not 
            (f_ok)))
        (not 
          (q_93t))
      )
    )
  (:action o_sync_q_94s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_94t))
    :effect
      (and
        (q_95t)
        (when
          (q_94s)
          (not 
            (q_94s)))
        (when
          (and
            (q_94s)
            (impurities_implantation))
          (not 
            (f_ok)))
        (not 
          (q_94t))
      )
    )
  (:action o_sync_q_95s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_95t))
    :effect
      (and
        (q_96t)
        (when
          (q_95s)
          (not 
            (q_95s)))
        (when
          (and
            (q_95s)
            (film_deposition))
          (not 
            (f_ok)))
        (not 
          (q_95t))
      )
    )
  (:action o_sync_q_96s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_96t))
    :effect
      (and
        (q_97t)
        (when
          (q_96s)
          (not 
            (q_96s)))
        (when
          (and
            (q_96s)
            (exposure))
          (not 
            (f_ok)))
        (not 
          (q_96t))
      )
    )
  (:action o_sync_q_97s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_97t))
    :effect
      (and
        (q_98t)
        (when
          (q_97s)
          (not 
            (q_97s)))
        (when
          (and
            (q_97s)
            (etching))
          (not 
            (f_ok)))
        (not 
          (q_97t))
      )
    )
  (:action o_sync_q_98s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_98t))
    :effect
      (and
        (q_99t)
        (when
          (q_98s)
          (not 
            (q_98s)))
        (when
          (and
            (q_98s)
            (development))
          (not 
            (f_ok)))
        (not 
          (q_98t))
      )
    )
  (:action o_sync_q_99s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_99t))
    :effect
      (and
        (q_100t)
        (when
          (q_99s)
          (not 
            (q_99s)))
        (when
          (and
            (q_99s)
            (cleaning))
          (not 
            (f_ok)))
        (not 
          (q_99t))
      )
    )
  (:action o_sync_q_100s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_100t))
    :effect
      (and
        (q_101t)
        (when
          (q_100s)
          (not 
            (q_100s)))
        (when
          (and
            (q_100s)
            (activation))
          (not 
            (f_ok)))
        (not 
          (q_100t))
      )
    )
  (:action o_sync_q_101s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_101t))
    :effect
      (and
        (q_102t)
        (when
          (q_101s)
          (not 
            (q_101s)))
        (when
          (and
            (q_101s)
            (not 
              (startsymb)))
          (not 
            (f_ok)))
        (not 
          (q_101t))
      )
    )
  (:action o_sync_q_102s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_102t))
    :effect
      (and
        (q_103t)
        (when
          (q_102s)
          (not 
            (q_102s)))
        (when
          (and
            (q_102s)
            (not 
              (resist_stripping)))
          (not 
            (f_ok)))
        (not 
          (q_102t))
      )
    )
  (:action o_sync_q_103s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_103t))
    :effect
      (and
        (q_104t)
        (when
          (q_103s)
          (not 
            (q_103s)))
        (when
          (and
            (q_103s)
            (not 
              (resist_coating)))
          (not 
            (f_ok)))
        (not 
          (q_103t))
      )
    )
  (:action o_sync_q_104s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_104t))
    :effect
      (and
        (q_105t)
        (when
          (q_104s)
          (not 
            (q_104s)))
        (when
          (and
            (q_104s)
            (not 
              (impurities_implantation)))
          (not 
            (f_ok)))
        (not 
          (q_104t))
      )
    )
  (:action o_sync_q_105s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_105t))
    :effect
      (and
        (q_106t)
        (when
          (q_105s)
          (not 
            (q_105s)))
        (when
          (and
            (q_105s)
            (not 
              (film_deposition)))
          (not 
            (f_ok)))
        (not 
          (q_105t))
      )
    )
  (:action o_sync_q_106s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_106t))
    :effect
      (and
        (q_107t)
        (when
          (q_106s)
          (not 
            (q_106s)))
        (when
          (and
            (q_106s)
            (not 
              (exposure)))
          (not 
            (f_ok)))
        (not 
          (q_106t))
      )
    )
  (:action o_sync_q_107s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_107t))
    :effect
      (and
        (q_108t)
        (when
          (q_107s)
          (not 
            (q_107s)))
        (when
          (and
            (q_107s)
            (not 
              (etching)))
          (not 
            (f_ok)))
        (not 
          (q_107t))
      )
    )
  (:action o_sync_q_108s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_108t))
    :effect
      (and
        (q_109t)
        (when
          (q_108s)
          (not 
            (q_108s)))
        (when
          (and
            (q_108s)
            (not 
              (development)))
          (not 
            (f_ok)))
        (not 
          (q_108t))
      )
    )
  (:action o_sync_q_109s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_109t))
    :effect
      (and
        (q_110t)
        (when
          (q_109s)
          (not 
            (q_109s)))
        (when
          (and
            (q_109s)
            (not 
              (cleaning)))
          (not 
            (f_ok)))
        (not 
          (q_109t))
      )
    )
  (:action o_sync_q_110s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_110t))
    :effect
      (and
        (q_111t)
        (when
          (q_110s)
          (not 
            (q_110s)))
        (when
          (and
            (q_110s)
            (not 
              (activation)))
          (not 
            (f_ok)))
        (not 
          (q_110t))
      )
    )
  (:action o_sync_q_111s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_111t))
    :effect
      (and
        (q_112t)
        (when
          (q_111s)
          (not 
            (q_111s)))
        (not 
          (q_111t))
      )
    )
  (:action o_sync_q_112s
    :parameters ()
    :precondition 
      (and
        (f_sync)
        (f_ok)
        (q_112t))
    :effect
      (and
        (f_world)
        (when
          (q_1s)
          (q_1))
        (when
          (q_2s)
          (q_2))
        (when
          (q_3s)
          (q_3))
        (when
          (q_4s)
          (q_4))
        (when
          (q_5s)
          (q_5))
        (when
          (q_6s)
          (q_6))
        (when
          (q_7s)
          (q_7))
        (when
          (q_8s)
          (q_8))
        (when
          (q_9s)
          (q_9))
        (when
          (q_10s)
          (q_10))
        (when
          (q_11s)
          (q_11))
        (when
          (q_12s)
          (q_12))
        (when
          (q_13s)
          (q_13))
        (when
          (q_14s)
          (q_14))
        (when
          (q_15s)
          (q_15))
        (when
          (q_16s)
          (q_16))
        (when
          (q_17s)
          (q_17))
        (when
          (q_18s)
          (q_18))
        (when
          (q_19s)
          (q_19))
        (when
          (q_20s)
          (q_20))
        (when
          (q_21s)
          (q_21))
        (when
          (q_22s)
          (q_22))
        (when
          (q_23s)
          (q_23))
        (when
          (q_24s)
          (q_24))
        (when
          (q_25s)
          (q_25))
        (when
          (q_26s)
          (q_26))
        (when
          (q_27s)
          (q_27))
        (when
          (q_28s)
          (q_28))
        (when
          (q_29s)
          (q_29))
        (when
          (q_30s)
          (q_30))
        (when
          (q_31s)
          (q_31))
        (when
          (q_32s)
          (q_32))
        (when
          (q_33s)
          (q_33))
        (when
          (q_34s)
          (q_34))
        (when
          (q_35s)
          (q_35))
        (when
          (q_36s)
          (q_36))
        (when
          (q_37s)
          (q_37))
        (when
          (q_38s)
          (q_38))
        (when
          (q_39s)
          (q_39))
        (when
          (q_40s)
          (q_40))
        (when
          (q_41s)
          (q_41))
        (when
          (q_42s)
          (q_42))
        (when
          (q_43s)
          (q_43))
        (when
          (q_44s)
          (q_44))
        (when
          (q_45s)
          (q_45))
        (when
          (q_46s)
          (q_46))
        (when
          (q_47s)
          (q_47))
        (when
          (q_48s)
          (q_48))
        (when
          (q_49s)
          (q_49))
        (when
          (q_50s)
          (q_50))
        (when
          (q_51s)
          (q_51))
        (when
          (q_52s)
          (q_52))
        (when
          (q_53s)
          (q_53))
        (when
          (q_54s)
          (q_54))
        (when
          (q_55s)
          (q_55))
        (when
          (q_56s)
          (q_56))
        (when
          (q_57s)
          (q_57))
        (when
          (q_58s)
          (q_58))
        (when
          (q_59s)
          (q_59))
        (when
          (q_60s)
          (q_60))
        (when
          (q_61s)
          (q_61))
        (when
          (q_62s)
          (q_62))
        (when
          (q_63s)
          (q_63))
        (when
          (q_64s)
          (q_64))
        (when
          (q_65s)
          (q_65))
        (when
          (q_66s)
          (q_66))
        (when
          (q_67s)
          (q_67))
        (when
          (q_68s)
          (q_68))
        (when
          (q_69s)
          (q_69))
        (when
          (q_70s)
          (q_70))
        (when
          (q_71s)
          (q_71))
        (when
          (q_72s)
          (q_72))
        (when
          (q_73s)
          (q_73))
        (when
          (q_74s)
          (q_74))
        (when
          (q_75s)
          (q_75))
        (when
          (q_76s)
          (q_76))
        (when
          (q_77s)
          (q_77))
        (when
          (q_78s)
          (q_78))
        (when
          (q_79s)
          (q_79))
        (when
          (q_80s)
          (q_80))
        (when
          (q_81s)
          (q_81))
        (when
          (q_82s)
          (q_82))
        (when
          (q_83s)
          (q_83))
        (when
          (q_84s)
          (q_84))
        (when
          (q_85s)
          (q_85))
        (when
          (q_86s)
          (q_86))
        (when
          (q_87s)
          (q_87))
        (when
          (q_88s)
          (q_88))
        (when
          (q_89s)
          (q_89))
        (when
          (q_90s)
          (q_90))
        (when
          (q_91s)
          (q_91))
        (when
          (q_92s)
          (q_92))
        (when
          (q_93s)
          (q_93))
        (when
          (q_94s)
          (q_94))
        (when
          (q_95s)
          (q_95))
        (when
          (q_96s)
          (q_96))
        (when
          (q_97s)
          (q_97))
        (when
          (q_98s)
          (q_98))
        (when
          (q_99s)
          (q_99))
        (when
          (q_100s)
          (q_100))
        (when
          (q_101s)
          (q_101))
        (when
          (q_102s)
          (q_102))
        (when
          (q_103s)
          (q_103))
        (when
          (q_104s)
          (q_104))
        (when
          (q_105s)
          (q_105))
        (when
          (q_106s)
          (q_106))
        (when
          (q_107s)
          (q_107))
        (when
          (q_108s)
          (q_108))
        (when
          (q_109s)
          (q_109))
        (when
          (q_110s)
          (q_110))
        (when
          (q_111s)
          (q_111))
        (when
          (q_112s)
          (q_112))
        (when
          (q_112s)
          (not 
            (f_ok)))
        (not 
          (q_112t))
        (not 
          (f_sync))
        (not 
          (q_1s))
        (not 
          (q_2s))
        (not 
          (q_3s))
        (not 
          (q_4s))
        (not 
          (q_5s))
        (not 
          (q_6s))
        (not 
          (q_7s))
        (not 
          (q_8s))
        (not 
          (q_9s))
        (not 
          (q_10s))
        (not 
          (q_11s))
        (not 
          (q_12s))
        (not 
          (q_13s))
        (not 
          (q_14s))
        (not 
          (q_15s))
        (not 
          (q_16s))
        (not 
          (q_17s))
        (not 
          (q_18s))
        (not 
          (q_19s))
        (not 
          (q_20s))
        (not 
          (q_21s))
        (not 
          (q_22s))
        (not 
          (q_23s))
        (not 
          (q_24s))
        (not 
          (q_25s))
        (not 
          (q_26s))
        (not 
          (q_27s))
        (not 
          (q_28s))
        (not 
          (q_29s))
        (not 
          (q_30s))
        (not 
          (q_31s))
        (not 
          (q_32s))
        (not 
          (q_33s))
        (not 
          (q_34s))
        (not 
          (q_35s))
        (not 
          (q_36s))
        (not 
          (q_37s))
        (not 
          (q_38s))
        (not 
          (q_39s))
        (not 
          (q_40s))
        (not 
          (q_41s))
        (not 
          (q_42s))
        (not 
          (q_43s))
        (not 
          (q_44s))
        (not 
          (q_45s))
        (not 
          (q_46s))
        (not 
          (q_47s))
        (not 
          (q_48s))
        (not 
          (q_49s))
        (not 
          (q_50s))
        (not 
          (q_51s))
        (not 
          (q_52s))
        (not 
          (q_53s))
        (not 
          (q_54s))
        (not 
          (q_55s))
        (not 
          (q_56s))
        (not 
          (q_57s))
        (not 
          (q_58s))
        (not 
          (q_59s))
        (not 
          (q_60s))
        (not 
          (q_61s))
        (not 
          (q_62s))
        (not 
          (q_63s))
        (not 
          (q_64s))
        (not 
          (q_65s))
        (not 
          (q_66s))
        (not 
          (q_67s))
        (not 
          (q_68s))
        (not 
          (q_69s))
        (not 
          (q_70s))
        (not 
          (q_71s))
        (not 
          (q_72s))
        (not 
          (q_73s))
        (not 
          (q_74s))
        (not 
          (q_75s))
        (not 
          (q_76s))
        (not 
          (q_77s))
        (not 
          (q_78s))
        (not 
          (q_79s))
        (not 
          (q_80s))
        (not 
          (q_81s))
        (not 
          (q_82s))
        (not 
          (q_83s))
        (not 
          (q_84s))
        (not 
          (q_85s))
        (not 
          (q_86s))
        (not 
          (q_87s))
        (not 
          (q_88s))
        (not 
          (q_89s))
        (not 
          (q_90s))
        (not 
          (q_91s))
        (not 
          (q_92s))
        (not 
          (q_93s))
        (not 
          (q_94s))
        (not 
          (q_95s))
        (not 
          (q_96s))
        (not 
          (q_97s))
        (not 
          (q_98s))
        (not 
          (q_99s))
        (not 
          (q_100s))
        (not 
          (q_101s))
        (not 
          (q_102s))
        (not 
          (q_103s))
        (not 
          (q_104s))
        (not 
          (q_105s))
        (not 
          (q_106s))
        (not 
          (q_107s))
        (not 
          (q_108s))
        (not 
          (q_109s))
        (not 
          (q_110s))
        (not 
          (q_111s))
        (not 
          (q_112s))
      )
    )
)