(define (domain composition)
  (:requirements :strips :typing :non-deterministic :conditional-effects)
  (:types state action)
  (:constants
    s0_rotor_builder_0 - state
    s1_stator_builder_0 - state
    s2_inverter_builder_0 - state
    s3_motor_assembler_0 - state
    s4_painter_0 - state
    s5_runner_0 - state
    s6_electric_tester_0 - state
    s7_static_tester_0 - state
  )
  (:predicates
    (current_state_0 ?s - state)
    (current_state_1 ?s - state)
    (current_state_2 ?s - state)
    (current_state_3 ?s - state)
    (current_state_4 ?s - state)
    (current_state_5 ?s - state)
    (current_state_6 ?s - state)
    (current_state_7 ?s - state)
    (assemble_motor)
    (build_retrieve_inverter)
    (build_retrieve_rotor)
    (build_retrieve_stator)
    (electric_test)
    (painting)
    (running_in)
    (static_test)
    (startsymb)
  )
(:action assemble_motor_3_motor_assembler_0
    :precondition (current_state_3 s3_motor_assembler_0)
    :effect (and
            (current_state_3 s3_motor_assembler_0)
        (assemble_motor)
        (not (build_retrieve_inverter))
        (not (build_retrieve_rotor))
        (not (build_retrieve_stator))
        (not (electric_test))
        (not (painting))
        (not (running_in))
        (not (static_test))
    )
)
(:action build_retrieve_inverter_2_inverter_builder_0
    :precondition (current_state_2 s2_inverter_builder_0)
    :effect (and
            (current_state_2 s2_inverter_builder_0)
        (build_retrieve_inverter)
        (not (assemble_motor))
        (not (build_retrieve_rotor))
        (not (build_retrieve_stator))
        (not (electric_test))
        (not (painting))
        (not (running_in))
        (not (static_test))
    )
)
(:action build_retrieve_rotor_0_rotor_builder_0
    :precondition (current_state_0 s0_rotor_builder_0)
    :effect (and
            (current_state_0 s0_rotor_builder_0)
        (build_retrieve_rotor)
        (not (assemble_motor))
        (not (build_retrieve_inverter))
        (not (build_retrieve_stator))
        (not (electric_test))
        (not (painting))
        (not (running_in))
        (not (static_test))
    )
)
(:action build_retrieve_stator_1_stator_builder_0
    :precondition (current_state_1 s1_stator_builder_0)
    :effect (and
            (current_state_1 s1_stator_builder_0)
        (build_retrieve_stator)
        (not (assemble_motor))
        (not (build_retrieve_inverter))
        (not (build_retrieve_rotor))
        (not (electric_test))
        (not (painting))
        (not (running_in))
        (not (static_test))
    )
)
(:action electric_test_6_electric_tester_0
    :precondition (current_state_6 s6_electric_tester_0)
    :effect (and
            (current_state_6 s6_electric_tester_0)
        (electric_test)
        (not (assemble_motor))
        (not (build_retrieve_inverter))
        (not (build_retrieve_rotor))
        (not (build_retrieve_stator))
        (not (painting))
        (not (running_in))
        (not (static_test))
    )
)
(:action painting_4_painter_0
    :precondition (current_state_4 s4_painter_0)
    :effect (and
            (current_state_4 s4_painter_0)
        (painting)
        (not (assemble_motor))
        (not (build_retrieve_inverter))
        (not (build_retrieve_rotor))
        (not (build_retrieve_stator))
        (not (electric_test))
        (not (running_in))
        (not (static_test))
    )
)
(:action running_in_5_runner_0
    :precondition (current_state_5 s5_runner_0)
    :effect (and
            (current_state_5 s5_runner_0)
        (running_in)
        (not (assemble_motor))
        (not (build_retrieve_inverter))
        (not (build_retrieve_rotor))
        (not (build_retrieve_stator))
        (not (electric_test))
        (not (painting))
        (not (static_test))
    )
)
(:action static_test_7_static_tester_0
    :precondition (current_state_7 s7_static_tester_0)
    :effect (and
            (current_state_7 s7_static_tester_0)
        (static_test)
        (not (assemble_motor))
        (not (build_retrieve_inverter))
        (not (build_retrieve_rotor))
        (not (build_retrieve_stator))
        (not (electric_test))
        (not (painting))
        (not (running_in))
    )
)
  )
