(define (problem problem)

  (:domain 'domain-problem')
  (:objects s0_handler_cleaning_0 - state s0_handler_cleaning_broken - state s1_handler_film_deposition_0 - state s1_handler_film_deposition_broken - state s2_handler_resist_coating_0 - state s2_handler_resist_coating_broken - state s3_handler_exposure_0 - state s3_handler_exposure_broken - state s4_handler_development_0 - state s4_handler_development_broken - state s5_handler_etching_0 - state s5_handler_etching_broken - state)
  (:init 
    (current_state_0 s0_handler_cleaning_0)
    (current_state_1 s1_handler_film_deposition_0)
    (current_state_2 s2_handler_resist_coating_0)
    (current_state_3 s3_handler_exposure_0)
    (current_state_4 s4_handler_development_0)
    (current_state_5 s5_handler_etching_0)
    (startsymb)
    (q_1)
    (f_copy)
    (f_ok)
  )
  (:goal (and (current_state_0 s0_handler_cleaning_0)  (current_state_1 s1_handler_film_deposition_0)  (current_state_2 s2_handler_resist_coating_0)  (current_state_3 s3_handler_exposure_0)  (current_state_4 s4_handler_development_0)  (current_state_5 s5_handler_etching_0) 
    (not 
      (q_57))
    (q_1d)
    (q_50d)
    (q_2d)
    (q_3d)
    (q_4d)
    (q_56d)
    (q_5d)
    (q_45d)
    (q_6d)
    (q_44d)
    (q_7d)
    (q_46d)
    (q_8d)
    (q_48d)
    (q_9d)
    (q_10d)
    (q_11d)
    (q_52d)
    (q_12d)
    (q_49d)
    (q_13d)
    (q_44d)
    (q_14d)
    (q_46d)
    (q_15d)
    (q_48d)
    (q_16d)
    (q_17d)
    (q_18d)
    (q_51d)
    (q_19d)
    (q_49d)
    (q_20d)
    (q_45d)
    (q_21d)
    (q_46d)
    (q_22d)
    (q_48d)
    (q_23d)
    (q_24d)
    (q_25d)
    (q_53d)
    (q_26d)
    (q_49d)
    (q_27d)
    (q_45d)
    (q_28d)
    (q_44d)
    (q_29d)
    (q_48d)
    (q_30d)
    (q_31d)
    (q_32d)
    (q_55d)
    (q_33d)
    (q_49d)
    (q_34d)
    (q_45d)
    (q_35d)
    (q_44d)
    (q_36d)
    (q_46d)
    (q_37d)
    (q_38d)
    (q_39d)
    (q_54d)
    (q_40d)
    (q_49d)
    (q_41d)
    (q_45d)
    (q_42d)
    (q_44d)
    (q_43d)
    (q_48d)
    (q_46d)
    (q_47d)
    (q_47d)
    (q_47d)
    (q_47d)
    (q_47d)))

)